name = "orange-meets"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"
account_id = "cc269d87f9e3fcb00cee88bc3a18c4c4"
main = "./build/index.js"

[site]
  bucket = "./public"

[[build.upload.rules]]
  type = "ESModule"
  globs = ["**/*.js"]

[vars]
CALLS_APP_ID = "9e4b4c3508dfd4d741538f037ae2fa17"

[durable_objects]
 bindings = [
  { name = "rooms", class_name = "ChatRoom" }
]

# Indicate that you want the ChatRoom class to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom"]

# The necessary secrets are:
# - CALLS_APP_SECRET
# To add secret, run `echo <VALUE> | wrangler secret put <NAME>`
